services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:123456@db/test
      - SECRET_KEY=your_secret_key
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=123456 
      - MYSQL_DATABASE=test         
    ports:
      - "3333:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
